---
# Widgets affichés en haut de page.
# Doc : https://gethomepage.dev/widgets/

- resources:
    cpu: true
    memory: true
    disk: /
    label: VPS

- datetime:
    text_size: xl
    locale: fr
    format:
      timeStyle: short
      dateStyle: full
      hour12: false
